sudo: false
language: java

before_install:
    # Temp workaround to remove old references to codehaus repos
- rm ~/.m2/settings.xml

jdk:
  # - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install:
  - git clone https://github.com/pgleeson/expr-parser.git
  - cd expr-parser
  - mvn install
  - cd $TRAVIS_BUILD_DIR 


 


